In [1]:
import numpy as np
np.__version__

'1.24.2'

In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1)
print(arr1.dtype)
print(arr2)
print(arr2.dtype)

[1 2 3]
int32
[[1 2]
 [3 4]]
int32


In [5]:
arr1 = np.array([1, 2, 3], np.int8)
arr2 = np.array([1, 2, 3], dtype=np.float16)
print(arr1)
print(arr1.dtype)
print(arr2)
print(arr2.dtype)

[1 2 3]
int8
[1. 2. 3.]
float16


In [9]:
print(np.empty(2))
print(np.empty((2, 2)))
print()

print(np.zeros(2))
print(np.zeros((2, 2)))
print()

print(np.ones(2))
print(np.ones((2, 2)))

[1.33590063e-311 1.33590063e-311]
[[2.12199579e-314 1.33473535e-311]
 [2.88534337e-321 1.33473535e-311]]

[0. 0.]
[[0. 0.]
 [0. 0.]]

[1. 1.]
[[1. 1.]
 [1. 1.]]


In [13]:
print(np.full(2, 2))
print(np.full((2, 2), 2))
print()

print(np.identity(2))
print()

print(np.eye(2))
print(np.eye(2, 2))
print(np.eye(4, 3))

[2 2]
[[2 2]
 [2 2]]

[[1. 0.]
 [0. 1.]]

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [24]:
print(np.arange(1, 5))
print(np.linspace(0, 10, 5))
print(np.logspace(0, 2, 3))
print(np.geomspace(1, 100, 3))

[1 2 3 4]
[ 0.   2.5  5.   7.5 10. ]
[  1.  10. 100.]
[  1.  10. 100.]


In [32]:
print(np.fromstring('abc', dtype=np.int8))
print(np.fromstring('abc', dtype='S1'))
print(np.fromstring('abcd', dtype='S2'))
print(np.fromstring('abcdabcd', dtype='U2'))

[97 98 99]
[b'a' b'b' b'c']
[b'ab' b'cd']
['\U64636261\U64636261']


C:\Users\Administrator\AppData\Local\Temp\ipykernel_11948\2565437813.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  print(np.fromstring('abc', dtype=np.int8))
C:\Users\Administrator\AppData\Local\Temp\ipykernel_11948\2565437813.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  print(np.fromstring('abc', dtype='S1'))
C:\Users\Administrator\AppData\Local\Temp\ipykernel_11948\2565437813.py:3: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  print(np.fromstring('abcd', dtype='S2'))
C:\Users\Administrator\AppData\Local\Temp\ipykernel_11948\2565437813.py:4: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  print(np.fromstring('abcdabcd', 

In [45]:
print(np.frombuffer(b'abcdabcd'))
print(np.frombuffer(bytes('abcd', encoding='utf8'), dtype=np.int8))
print(np.frombuffer(bytes('abc', encoding='utf8'), dtype='S1', count=3, offset=0))
print(np.fromiter(range(5), np.int8))
print(np.fromfunction(np.abs, (2,)))
print(np.fromfunction(np.abs, (2,2)))

[3.83546108e+175]
[ 97  98  99 100]
[b'a' b'b' b'c']
[0 1 2 3 4]
[0. 1.]
[[0. 0.]
 [1. 1.]]


In [ ]:
print(np.loadtxt('a.txt'))

In [46]:
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

(3,)
3
int8


In [47]:
arr2 = arr1.astype(np.int16)
print(arr2.dtype)

int16


In [54]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int8)
print(arr1)
print(arr1.T)
print(arr1.transpose())
print(arr1.ravel()) # 共享内存
print(arr1.flatten()) # 不共享内存

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [56]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b.T), axis=1))
print(np.concatenate((a, b), axis=None))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]


In [61]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.vstack((a, b)))
print(np.hstack((a, b)))
print(np.column_stack((a, b)))
print(np.dstack((a, b))) # 增加一维

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [68]:
x = np.arange(9)
print(np.split(x, 3))
print(np.array_split(x, 4))

x = np.arange(8).reshape(4, 2)
print(x)
print(np.vsplit(x, 2))
print(np.hsplit(x, 2))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[array([[0, 1],
       [2, 3]]), array([[4, 5],
       [6, 7]])]
[array([[0],
       [2],
       [4],
       [6]]), array([[1],
       [3],
       [5],
       [7]])]
